<?php

namespace Prodeko\IlmoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuotaInEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotaInEventRepository extends EntityRepository
{
}