<?php

namespace Prodeko\IlmoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TapahtumaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TapahtumaRepository extends EntityRepository
{
}