<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/08 16:45:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ilmodb',
  'username' => 'root',
  'password' => 'h0monaama',
  'name' => 'doctrine',
)),);
