Prodeko\IlmoBundle\Entity\Event:
  type: entity
  table: event_table
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
    takesPlace:
      type: datetime
      nullable: true
    registrationStarts:
      type: datetime
      nullable: true
    registrationEnds:
      type: datetime
      nullable: true
    location:
      type: string
      length: 50
      nullable: true
    summary:
      type: string
      length: 160
    description:
      type: text
    kiltisilmo:
      type: boolean
      nullable: true
  manyToMany:
    freeTextFields:
      targetEntity: FreeTextField
      inversedBy: events
      cascade: ["persist"]

  oneToMany:
    registrations:
      targetEntity: Registration
      mappedBy: event
    quotas:
      targetEntity: Quota
      mappedBy: event
      cascade: [persist]
  lifecycleCallbacks: {  }
