Prodeko\IlmoBundle\Entity\Event:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: '255'
    description:
      type: text
      length: null
    short_description:
      type: text
      length: null
  lifecycleCallbacks: {  }
