Prodeko\IlmoBundle\Entity\Event:
  type: entity
  table: event_table
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
    takes_place:
      type: datetime
    registration_starts:
      type: datetime
    registration_ends:
      type: datetime
    location:
      type: string
      length: 50
    summary:
      type: string
      length: 160
    description:
      type: text
  manyToMany:
    free_text_fields:
      targetEntity: FreeTextField
      
  oneToMany:
    registrations:
      targetEntity: Registration
      mappedBy: event
  lifecycleCallbacks: {  }
