Prodeko\IlmoBundle\Entity\FreeTextField:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
    
    #this might be unneccessary?
    description:
      type: text
      nullable: TRUE
    
  oneToMany:
    entries:
      targetEntity: FreeTextEntry
      mappedBy: field
      
  lifecycleCallbacks: {  }
