Prodeko\IlmoBundle\Entity\FreeTextEntry:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    content:
      type: text
      nullable: TRUE
  manyToOne:
    field:
      targetEntity: FreeTextField
      inversedBy: entries
    registration:
      targetEntity: Registration
      inversedBy: freeTextEntries
      
  lifecycleCallbacks: {  }
