Prodeko\IlmoBundle\Entity\FreeTextContent:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    content:
      type: text
  
  lifecycleCallbacks: {  }
