Prodeko\IlmoBundle\Entity\Ilmoittautuminen:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    timestamp:
      type: datetime
  manyToOne:
    tapahtuma:
      targetEntity: Tapahtuma
      inversedBy: ilmoittautumiset
      joinColumn:
        name: tapahtuma_id
        referencedColumnName: id
  manyToOne:
    kayttaja:
      targetEntity: Kayttaja
      inversedBy: ilmoittautumiset
      joinColumn:
        name: kayttaja_id
        referencedColumnName: id
  lifecycleCallbacks: {  }
