Prodeko\IlmoBundle\Entity\Kayttaja:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    firstname:
      type: string
      length: '50'
    lastname:
      type: string
      length: '50'
    external_id:
      type: string
      length: 255
    year_of_studies:
      type: smallint
    email:
      type: string
      length: 255
  oneToMany:
    ilmoittautumiset:
      targetEntity: Ilmoittautuminen
      mappedBy: kayttaja
  lifecycleCallbacks: {  }
