Prodeko\IlmoBundle\Entity\MultipleChoiceField:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
    choices:
      type: array
    flagPrivate:
      type: boolean
      
  oneToMany:
    entries:
      targetEntity: MultipleChoiceEntry
      mappedBy: field
      cascade: ["persist"]
  manyToMany:
    events:
      targetEntity: Event
      cascade: ["persist"]
      mappedBy: multipleChoiceFields
      
  lifecycleCallbacks: {  }
