Prodeko\IlmoBundle\Entity\MultipleChoiceEntry:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    selection:
      type: string
  manyToOne:
    registration:
      targetEntity: Registration
      inversedBy: multipleChoiceEntries
    field:
      targetEntity: MultipleChoiceField
      inversedBy: entries
      
  lifecycleCallbacks: {  }
