Prodeko\IlmoBundle\Entity\MultipleChoiceField:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
    choices:
      type: array
  lifecycleCallbacks: {  }
