Prodeko\IlmoBundle\Entity\Person:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    openId:
      type: string
      nullable: TRUE
    firstName:
      type: string
    lastName:
      type: string
    email:
      type: string
    
  oneToMany:
    registrations:
      targetEntity: Registration
      mappedBy: person
  
  lifecycleCallbacks: {  }
