Prodeko\IlmoBundle\Entity\Quota:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
    yearOfStudiesValue:
      type: integer
      nullable: true
    size:
      type: integer
  manyToOne:
    event:
      targetEntity: Event
      inversedBy: quotas
      cascade: [persist]
  oneToMany:
    registrations:
      targetEntity: Registration
      mappedBy: quota
  lifecycleCallbacks: {  }
