Prodeko\IlmoBundle\Entity\Registration:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    registrationTime:
      type: datetime
    firstName: 
      type: string
    lastName:
      type: string
    email:
      type: string
    phone:
      type: string
      nullable: TRUE
    allergies:
      type: string
      nullable: TRUE
    token:
      type: string

  manyToOne:
    event:
      targetEntity: Event
      inversedBy: registrations
    person:
      targetEntity: Person
      inversedBy: registrations
    quota:
      targetEntity: Quota
      inversedBy: registrations
  oneToMany:
    freeTextEntries:
      targetEntity: FreeTextEntry
      mappedBy: registration
      cascade: [persist]
    multipleChoiceEntries:
      targetEntity: MultipleChoiceEntry
      mappedBy: registration
      cascade: [persist]
      
  lifecycleCallbacks: {  }
