Prodeko\IlmoBundle\Entity\Tapahtuma:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
    description:
      type: text
    takes_place:
      type: datetime
    registration_starts:
      type: datetime
    registration_ends:
      type: datetime
  lifecycleCallbacks: {  }
