list:
    pattern: /list/
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:list }
    
show:
    pattern: /show/{id}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:show }

create:
    pattern: /create/
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:createEventForm }

createEvent:
    pattern: /createEvent/
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:createEvent }
    