list:
    pattern: /list/
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:list }
    
show:
    pattern: /show/{id}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:show }

create:
    pattern: /create/{id}
    defaults: { _controller: ProdekoIlmoBundle:Admin:createEventForm, id: 0 }

createEvent:
    pattern: /createEvent/
    defaults: { _controller: ProdekoIlmoBundle:Admin:createEvent }
    