login:
    pattern: /login
    defaults: { _controller: ProdekoIlmoBundle:Admin:login }
check:
    pattern: /check
logout:
    pattern: /logout

list:
    pattern: /{_locale}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:list, _locale: fi }
    requirements:
      _locale: en|fi|spurdo
      
show:
    pattern: /{_locale}/{id}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:show, _locale: fi  }
    requirements:
      _locale: en|fi|spurdo
      
register:
    pattern: /{_locale}/register/{id}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:register, _locale: fi }
    
removePrompt:
    pattern: /{_locale}/remove/{token}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:removePrompt, _locale: fi  }
    requirements:
      _locale: en|fi|spurdo
      
remove:
    pattern: /{_locale}/confirmremove/{token}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:removeRegistration, _locale: fi } 
    
queue:
    pattern: /{_locale}/queue/{id}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:queue, _locale: fi }
      
create:
    pattern: /{_locale}/admin/create/{id}
    defaults: { _controller: ProdekoIlmoBundle:Admin:createEventForm, id: 0, _locale: fi  }
    requirements:
      _locale: en|fi|spurdo
      
edit:
    pattern: /{_locale}/admin/edit/{id}
    defaults: { _controller: ProdekoIlmoBundle:Admin:createEventForm, _locale: fi }
    requirements:
      _locale: en|fi|spurdo
      
export:
    pattern: /{_locale}/admin/export/{id}
    defaults: { _controller: ProdekoIlmoBundle:Admin:export, _locale: fi }
    requirements:
      _locale: en|fi|spurdo

admin:
    pattern: /{_locale}/admin
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:list, _locale: fi }

admin_default:
  pattern: /admin
  defaults:  
      _controller: FrameworkBundle:Redirect:redirect
      route: admin
      permanent: true
   
adminRegistrations:
    pattern: /{_locale}/admin/{id}
    defaults: { _controller: ProdekoIlmoBundle:Admin:adminRegistrations, _locale: fi  }
    requirements:
      _locale: en|fi|spurdo
      
sendEmail:
    pattern: /{_locale}/admin/email/{id}
    defaults: { _controller: ProdekoIlmoBundle:Admin:sendEmail }