list:
    pattern: /{_locale}/list/
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:list, _locale: fi }
    requirements:
      _locale: en|fi|spurdo
show:
    pattern: /{_locale}/show/{id}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:show, _locale: fi  }
    requirements:
      _locale: en|fi|spurdo
      
create:
    pattern: /{_locale}/create/{id}
    defaults: { _controller: ProdekoIlmoBundle:Admin:createEventForm, id: 0, _locale: fi  }
    requirements:
      _locale: en|fi
      
createEvent:
    pattern: /{_locale}/createEvent
    defaults: { _controller: ProdekoIlmoBundle:Admin:createEvent, _locale: fi  }
    requirements:
      _locale: en|fi



######### kun localea ei anneta URL:ssa #########

list_default:
  pattern: /list
  defaults:  
      _controller: FrameworkBundle:Redirect:redirect
      route: list
      permanent: true
