list:
    pattern: /list/
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:list }
    
show:
    pattern: /show/{tapahtuma}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:show }

create:
    pattern: /create/
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:createEvent }
