list:
    pattern: /{_locale}/list/
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:list, _locale: fi }
    requirements:
      _locale: en|fi|spurdo
show:
    pattern: /{_locale}/show/{id}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:show, _locale: fi  }
    requirements:
      _locale: en|fi|spurdo
      
showFancy:
    pattern: /{_locale}/show/{name}/{id}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:show, _locale: fi  }
    requirements:
      _locale: en|fi|spurdo
      
create:
    pattern: /{_locale}/create/{id}
    defaults: { _controller: ProdekoIlmoBundle:Admin:createEventForm, id: 0, _locale: fi  }
    requirements:
      _locale: en|fi|spurdo
      
createEvent:
    pattern: /{_locale}/createEvent
    defaults: { _controller: ProdekoIlmoBundle:Admin:createEvent, _locale: fi  }
    requirements:
      _locale: en|fi|spurdo

removeRegistration:
    pattern: /{_locale}/remove/{token}
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:removeRegistration, _locale: fi  }
    requirements:
      _locale: en|fi
      
adminRegistrations:
    pattern: /{_locale}/adminRegistrations/{id}
    defaults: { _controller: ProdekoIlmoBundle:Admin:adminRegistrations, _locale: fi  }
    requirements:
      _locale: en|fi|spurdo
      
registrationSuccess:
    pattern: /success/{token}/
    defaults: { _controller: ProdekoIlmoBundle:Ilmo:registrationSuccess }


######### kun localea ei anneta URL:ssa #########

list_default:
  pattern: /list
  defaults:  
      _controller: FrameworkBundle:Redirect:redirect
      route: list
      permanent: true
