# Automaattisen lomakkeen tarkastuksen ehdot määritellään täällä
Prodeko\IlmoBundle\Entity\Registration:
    properties:
        firstName:
            - NotBlank: 
                message: Pakollinen kenttä!
        lastName:
            - NotBlank: 
                message: Pakollinen kenttä!
        email:
            - NotBlank:
                message: Pakollinen kenttä!
            - Email:
                message: Virheellinen osoite!
                
Prodeko\IlmoBundle\Entity\Event:
    properties:
        registrationStarts:
            - DateTime:
                message: Virheellinen aika!